# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Homeassistant Meshnet
version: "1.2.0"
slug: example
description: Homeassistant Meshnet
url: "https://github.com/pabloegpf1/ha-meshnet"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
